version: "3.1"
services: 
  api: 
    image: <image_name_from_docker_hub>
    depends_on:
      - postgres 
    ports: 
      - 80:8000
    # volumnes:
    #   - ./:/usr/src/app:ro ## ro is read only

    # command: uvcorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file: 
    #   - ./.env 
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    # hostname: fastapi
  
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - postgres-db:/var/lib/postgresql/data
    # platform: linux/arm/v7
    # hostname: postgres

volumes:
  postgres-db:
